name: GPU Workflow
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda
    steps:
      - name: Check GPU
        run: nvidia-smi
