name: Advanced-GPU-Workflow12

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.0-base
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python with GPU
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cuda-version: '11.0'
      - name: Install CUDA Toolkit
        run: |
          apt-get update
          apt-get install -y cuda
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-gpu
      - name: Run GPU Task
        run: python script.py
